# vim:filetype=dockerfile
# vim:syntax=dockerfile
FROM quay.io/toolbx-images/alpine-toolbox:edge

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with toolbox or distrobox" \
      summary="A cloud-native terminal experience" \
      maintainer="dperson@gmail.com"

COPY .github/extra-packages-alpine /tmp/extra-packages
RUN apk update && \
    apk upgrade && \
    grep -v '^#' /tmp/extra-packages | xargs apk add && \
    awk '/^#testing/ {print $2}' /tmp/extra-packages | xargs apk add \
          --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ && \
    rm /tmp/extra-packages && \
    URL="https://github.com/89luca89/distrobox/raw/main" && \
    for i in distrobox-export distrobox-host-exec distrobox-init; do \
      curl -LSs "$URL/$i" -o "/usr/bin/$i"; done && \
    mv /usr/bin/distrobox-init /usr/bin/entrypoint && \
    VER="$(sed -n '/host_spawn_version=/s/.*=//p' \
          /usr/bin/distrobox-host-exec)" && \
    URL="https://github.com/1player/host-spawn/releases/download" && \
    curl -LSs "$URL/$VER/host-spawn-$(uname -m)" -o /usr/bin/host-spawn && \
    for i in distrobox-export distrobox-host-exec entrypoint host-spawn; do \
      chmod +x "/usr/bin/$i"; done && \
    URL="https://api.github.com/repos/swsnr/mdcat/releases" && \
    F='.[0].assets[] | select(.name|test("linux")) | .browser_download_url' && \
    curl -LSs $(curl -LSs "$URL" | jq -r "$F") -o /tmp/mdcat.tgz && \
    { tar -C /tmp -xf /tmp/mdcat.tgz||:; }&&\
    cp /tmp/mdcat*/mdcat /usr/bin && \
    cp /tmp/mdcat*/mdcat.1 /usr/share/man/man1 && \
    F='.[0].assets[]|select(.name|test("x86_64.*lin"))|.browser_download_url'&&\
    URL="https://api.github.com/repos/aaronriekenberg/rust-parallel/releases"&&\
    curl -LSs "$(curl -LSs "${URL}" | jq -r "${F}")" -o /tmp/parallel.tgz && \
    tar -C /tmp -xf /tmp/parallel.tgz && \
    cp /tmp/rust-parallel /usr/bin/parallel && \
    rm -rf /tmp/mdcat* /tmp/*parallel* && \
    chmod +x /usr/bin/parallel && \
    curl -L https://github.com/NoahTheDuke/vim-just/raw/main/syntax/just.vim \
          -o /usr/share/nvim/runtime/syntax/just.vim && \
    ln -frs /bin/sh /usr/bin/sh && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/appman && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/distrobox && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/gext && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/gsettings && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/just && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/toolbox && \
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update &&\
    ln -frs /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open