# image will be published to ghcr.io/<user>/<name>
name: silver-ublue
# description will be included in the image's metadata
description: Custom silver/ublue build

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
# alt-tags:
#   - beta
image-version: 40 # latest is also supported if you want new updates ASAP
                  # also update config/scripts/image-info.sh

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    akmods: # List of all available kernel modules & versions/tags are here:
            # https://github.com/ublue-os/akmods
      - evdi
      - framework-laptop
      - ryzen-smu

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - dconf-update-service # a service unit that updates the dconf db on boot

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside
                       # the image while putting files in /etc/ is done on
                       # booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/karmab/kcli/repo/fedora-%OS_VERSION%/karmab-kcli-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

  - type: containerfile
    snippets:
      # k8s tools
      - COPY --from=cgr.dev/chainguard/dive:latest /usr/bin/dive /usr/bin/dive
      - COPY --from=cgr.dev/chainguard/flux:latest /usr/bin/flux /usr/bin/flux
      - COPY --from=cgr.dev/chainguard/helm:latest /usr/bin/helm /usr/bin/helm
      - COPY --from=cgr.dev/chainguard/ko:latest /usr/bin/ko /usr/bin/ko
      - COPY --from=cgr.dev/chainguard/kubectl:latest /usr/bin/kubectl
              /usr/bin/kubectl
      - COPY --from=cgr.dev/chainguard/minio-client:latest /usr/bin/mc
              /usr/bin/mc
      # install Ptyxis
      # install cosmic
      # install niri / waybar
      # install ProtonMail / ProtonPass
      # install topgrade
      # install wezterm
      - RUN { rpm-ostree install ptyxis || true; } &&
        rpm-ostree install
              https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm
              https://proton.me/download/PassDesktop/linux/x64/ProtonPass.rpm &&
        rpm-ostree install python3-pip &&
        pip install --prefix=/usr topgrade &&
        rpm-ostree install https://github.com/wez/wezterm/releases/download/nightly/wezterm-nightly-fedora40.rpm &&
        cp --no-dereference --preserve=links /usr/lib64/libdrm.so.2
              /usr/lib64/libdrm.so
        # rpm-ostree install cosmic-desktop &&
        # rpm-ostree install niri waybar &&

  - type: rpm-ostree
    install:
      # - micro
      # - starship
      - android-tools
      - bat
      - bpftop
      - bootc
      - btop
      - cage # waydroid
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-pcp
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - devpod
      - docker-compose
      - eza
      - fastfetch
      - fd-find
      - gnome-shell-extension-auto-power-profile
      - gnome-shell-extension-logo-menu
      - gh
      - git-delta
      - GraphicsMagick
      - input-leap
      - iotop-c
      - kcli
      - krb5-workstation
      - micropipenv
      - nautilus-open-any-terminal
      - neovim
      - nmap
      - nodejs-npm
      - playerctl
      - podman-docker
      - podman-tui
      - powertop
      - printer-driver-brlaser
      - python3-eyed3
      - python3-pip
      - python3-virtualenv
      - rclone
      - restic
      - ripgrep
      - ryzenadj
      - stress-ng
      - simple-scan
      - systemd-container
      - tailscale
      - tio
      - waydroid
      - wireguard-tools
      - wl-clipboard
      - wlr-randr
      - ykpers
      - yt-dlp
      - yubikey-manager
      - zenity
      - zoxide
      - zsh
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed due to dep issues
      - gnome-terminal
      - gnome-terminal-nautilus
      - gnome-tour

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (bool)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's
      #     user-facing name in graphical frontends like GNOME Software
      install:
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning  # This is an example of flatpak which
                                          # has multiple branches in selection
                                          # (flatpak//branch).
        # Flatpak runtimes are not supported (ie org.winehq.Wine//stable-23.08),
        # only normal flatpak applications are (ie Floorp Lightning web browser
        # in this example).
        # Installing different branches of the same Flatpak is not supported.
        - com.github.johnfactotum.Foliate # Foliate (eBook Reader)
        - com.github.rafostar.Clapper # Clapper (Media Player)
        - com.mattjakeman.ExtensionManager
        # - dev.geopjr.Calligraphy # ASCII graphics text
        - org.gnome.baobab # Disk Usage Analyzer
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.FileRoller
        - org.gnome.Firmware
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe # Image Viewer
        - org.gnome.Maps
        - org.gnome.meld # Merge Text
        - org.gnome.Mines
        - org.gnome.NautilusPreviewer # Sushi
        - org.gnome.NetworkDisplays
        - org.gnome.Papers # PDF / Document Viewer
        - org.gnome.Photos
        - org.gnome.Rhythmbox3 # Music Player
        - org.gnome.SimpleScan # Document Scanner
        - org.gnome.Snapshot # Camera
        - org.gnome.Sudoku
        - org.gnome.TextEditor
        - org.gnome.Weather
        ### System Apps
        - app.drey.KeyRack
        - com.github.tchx84.Flatseal # Flatpak Permission Manager
        - io.github.flattool.Warehouse
        # - io.github.prateekmedia.appimagepool # AppImage Installer
        - io.gitlab.adhami3310.Impression # Media Writer
        - io.missioncenter.MissionCenter
        - org.cockpit_project.CockpitClient
        - org.gnome.DejaDup # Backups
        ### Web Browsers
        # - com.brave.Browser # Brave
        - com.google.Chrome
        # - com.microsoft.Edge
        # - com.opera.Opera
        - com.vivaldi.Vivaldi
        - org.gnome.Epiphany # GNOME Web
        - org.mozilla.firefox
        - re.sonny.Junction
        - re.sonny.Tangram
        ### Communications
        - dev.geopjr.Tuba # Mastodon
        - im.dino.Dino # XMPP Client
        # - org.gnome.Calls # SIP / Element Client
        - org.gnome.Fractal # Element Client
        - org.signal.Signal
        ### Gaming
        # - com.heroicgameslauncher.hgl # Heroic Games Launcher
        - com.usebottles.bottles
        - com.valvesoftware.Steam
        - com.valvesoftware.Steam.Utility.steamtinkerlaunch
        # - de.hummdudel.Libellus # D&D rules
        - net.davidotek.pupgui2 # Proton Updater for Steam
        - org.freedesktop.Platform.VulkanLayer.gamescope
        - org.freedesktop.Platform.VulkanLayer.MangoHud # MangoHUD
        - xyz.armcord.ArmCord # Discord
        ### Media
        - com.github.geigi.cozy # Nature/White Noise Sounds
        - com.github.KRTirtho.Spotube # Spotify / YouTube Music Player
        - de.haeckerfelix.Shortwave # Internet Radio
        # - de.schmidhuberj.tubefeeder # YouTube Client
        - io.freetubeapp.FreeTube # YouTube Client
        - io.github.Pithos # Pandora Client
        - org.videolan.VLC # Media Player
        # - tv.kodi.Kodi
        ### Office
        - com.calibre_ebook.calibre # eBook Editor
        - com.github.IsmaelMartinez.teams_for_linux
        - com.slack.Slack
        - com.vixalien.sticky
        - io.github.mrvladus.List # ToDos
        - md.obsidian.Obsidian
        - org.libreoffice.LibreOffice
        # - org.mozilla.Thunderbird
        # - org.onlyoffice.desktopeditors # OnlyOffice
        - org.standardnotes.standardnotes
        - us.zoom.Zoom
        ### Development
        - ca.desrt.dconf-editor
        - io.github.dvlv.boxbuddyrs # Container Manager
        - io.podman_desktop.PodmanDesktop
        - org.gnome.Boxes # Simple VM Manager
        - org.gnome.Builder # Gnome IDE
        - re.sonny.Commit # Text Editor
        - re.sonny.Workbench # GTK4/libadwaita
        ### Graphics
        - com.github.maoschanz.drawing
        # - org.darktable.Darktable
        - org.gimp.GIMP
        # - org.inkscape.Inkscape
        # - org.kde.krita
        ### Media Production
        - fr.handbrake.ghb # Handbrake
        - org.audacityteam.Audacity
        - org.gnome.gitlab.YaLTeR.VideoTrimmer
        # - org.kde.kdenlive
        # - org.olivevideoeditor.Olive
        # - org.pitivi.Pitivi
        ### Streaming
        # - com.feaneron.Boatswain # Boatswain for Streamdeck
        # - com.obsproject.Studio # OBS Studio
        # - com.obsproject.Studio.OBSVkCapture # VkCapture (OBS)
        # - com.obsproject.Studio.Plugin.Gstreamer # Gstreamer (OBS)
        # - com.obsproject.Studio.Plugin.GStreamerVaapi # Gstreamer VAAPI (OBS)
        ### Utilities
        - com.ekonomikas.merkato # Stock Tracker
        - com.protonvpn.www # Proton VPN
        - de.haeckerfelix.Fragments # Bittorrent Client
        # - org.keepassxc.KeePassXC
        - xyz.safeworlds.hiit # Exercise Timer
      remove:
        - org.gnome.Evince

    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub

  - type: brew
    # Control Brew analytics
    brew-analytics: false # Optional - Default: true - Expects type: boolean

  - type: gschema-overrides
    include:
      - ublue1.gschema.override
      - ublue2.gschema.override

  - type: systemd
    system:
      enabled:
        - btrfs-dedup.timer
        - podman.socket
        - podman-auto-update.timer
        - rpm-ostree-countme.service
        - ryzenadj.service
        - swtpm-workaround.service
        - tailscaled.service
        - ublue-etc-merge.service
        - ublue-system-setup.service

  - type: script
    scripts:
      - fonts.sh        # installs the desired fonts
      - image-info.sh   # create /usr/share/ublue-os/image-info.json
      - misc.sh         # misc tweaks to the system
      - quadlets.sh     # sets up ptyxis for containers

  - type: signing       # this sets up the proper policy & signing files for
                        # signed images to work fully