#!/usr/bin/env -S bash

# Enable NTP
timedatectl set-ntp true

# Allow Tailscale Control
tailscale set --operator="$(getent passwd "$PKEXEC_UID" | cut -d: -f1)"

# Allow libvirt access
wheelarray=($(getent group wheel | cut -d ":" -f 4 | tr ',' '\n'))
for user in $wheelarray; do
  usermod -aG libvirt $user
done