[include]
paths = ["/etc/ublue-os/topgrade.toml"]

[misc]
no_self_update = true
disable = ["self_update", "toolbx", "containers", "system"]
ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "node", "pip3", "helm", "home_manager", "firmware"]
assume_yes = true
no_retry = false

[commands]
"System Upgrade" = "sudo bootc upgrade"