#!/usr/bin/env bash

source /etc/default/waydroid-launcher
source /etc/default/steamos-nested-desktop

# Ensure needed props are present
file="/var/lib/waydroid/waydroid_base.prop"

if ! grep -q "persist.waydroid.udev=true" "${file}"; then
  sudo sh -c 'echo -e "persist.waydroid.udev=true" >>'"${file}"
fi

if ! grep -q "persist.waydroid.uevent=true" "${file}"; then
  sudo sh -c 'echo -e "persist.waydroid.uevent=true" >>'"${file}"
fi

if [[ -n "$WAYDROID_DENSITY" ]]; then
  sudo sed -i "s/ro.sf.lcd_density=.*/ro.sf.lcd_density=${WAYDROID_DENSITY}/g" \
        /var/lib/waydroid/waydroid_base.prop
fi
sudo sed -i "s/ro.hardware.gralloc=.*/ro.hardware.gralloc=${WAYDROID_GRALLOC:-minigbm_gbm_mesa}/g" /var/lib/waydroid/waydroid_base.prop

# Add controller fixes automatically
if [[ -f "/usr/share/ublue-os/waydroid/Vendor_28de_Product_11ff.kl" ]]; then
  mkdir -p "/var/lib/waydroid/overlay/system/usr/keylayout"
  cp "/usr/share/ublue-os/waydroid/Vendor_28de_Product_11ff.kl" \
        "/var/lib/waydroid/overlay/system/usr/keylayout/"
fi

sudo systemctl start waydroid-container.service