name: Latest Images
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*iso*.yml"
      - ".github/workflows/*validate*.yml"
      - "build_files/iso/**"
  push:
    branches:
      - main
      - testing
    paths-ignore:
      - "**.md"
      - ".github/workflows/*iso*.yml"
      - ".github/workflows/*validate*.yml"
      - "build_files/iso/**"
  schedule:
    - cron: "30 5 * * *" # 05:30 UTC
  workflow_call:
  workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
  build-image-latest:
    name: Build Latest Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["silver-ublue"]
    with:
      image_flavors: '["main", "nvidia-open"]' # "nvidia",
      brand_name: ${{ matrix.brand_name }}
      stream_name: latest

  # generate-release:
  #   name: Generate Release
  #   needs: [build-image-latest]
  #   secrets: inherit
  #   uses: ./.github/workflows/generate-release.yml
  #   with:
  #     stream_name: '["latest"]'