name: bluebuild
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "40 4 * * *"  # build at 04:40 UTC every day
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      - '.github/Containerfile*'
      - '.github/extra-packages*'
      - '.github/workflows/boxkit.yml'
      - 'LICENSE'
      - 'CODEOWNERS'
  pull_request:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      - '.github/Containerfile*'
      - '.github/extra-packages*'
      - '.github/workflows/boxkit.yml'
      - 'LICENSE'
      - 'CODEOWNERS'
  workflow_call:
  workflow_dispatch: # allow manually triggering builds

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from canceling all matrix builds if one fails
      matrix:
        recipe: # !! Add your recipes here
          # - recipe-beta.yml
          - recipe-gts.yml
          - recipe.yml
    steps: # the build is fully handled by the reusable GitHub action
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          # enabled by default, disable with small images for faster builds
          #maximize_build_space: false
          pr_event_number: ${{ github.event.number }}
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          squash: true

  build_iso:
    name: build iso
    needs: bluebuild
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/iso.yml