name: Generate ISO

on:
  schedule:
    - cron: "30 17 * * *"
  push:
    paths:
      - "boot_menu.yml"
      - ".github/workflows/release-iso.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  release-iso:
    name: Generate and Release ISOs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    container:
      image: fedora:${{ matrix.major_version }}
      options: --privileged
      volumes:
        - "/:/host"
    strategy:
      fail-fast: false
      matrix:
        image_name: [silver-ublue]
        major_version: [39]
        image_tag: [latest]
    steps:
      - name: Build ISOs
        uses: ublue-os/isogenerator@1.0.7
        with:
          ARCH: 'x86_64'
          IMAGE_NAME: ${{ matrix.image_name }}
          IMAGE_REPO: ghcr.io/${{ github.repository_owner }}
          VARIANT: 'Silverblue'
          VERSION: ${{ matrix.major_version }}
          IMAGE_TAG: ${{ matrix.image_tag }}
          ACTION_REPO: ublue-os/isogenerator
          ACTION_REF: 1.0.7
