name: Validate Brewfiles
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "build_files/validate-brewfiles.sh"
      - "system_files/usr/share/ublue-os/homebrew/**"
      - ".github/workflows/validate-brewfiles.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@e99025eb970cfa124b8284a35463d87426917478 # main

      - name: Validate Brewfiles
        shell: bash
        run: bash build_files/validate-brewfiles.sh
